# Generated by Django 3.2.16 on 2023-02-16 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
